# Generated by Django 5.2.7 on 2025-10-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_countries', models.IntegerField(default=0)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'app status',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('population', models.BigIntegerField()),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=512, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('estimated_gdp', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
