# Generated by Django 5.2.7 on 2025-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppStatus',
            new_name='Status',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='country',
            name='currency_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='estimated_gdp',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='last_refreshed_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
